# Generated by Django 5.2.5 on 2025-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_photo",
        ),
    ]
