# Generated by Django 5.2.5 on 2025-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_customuser_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(max_length=200),
        ),
    ]
