# Generated by Django 5.2.4 on 2025-08-23 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                related_name="following_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="followers",
            field=models.ManyToManyField(
                related_name="user_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
