# Generated by Django 5.2.4 on 2025-08-21 12:12

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_created_date_comment_created_at_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
